// Monthly stock order sheet, grouped by supplier — seed data
const monthlyStock = [
  {
    supplier: "BWY Wilmar",
    items: [
      { name: "Unsalted Butter (454g/pc) (20pc/ctn)", unit: "CTN" },
      { name: "Japonica Rice (25kg/pkt)", unit: "PKT" },
    ],
  },
  {
    supplier: "Oregano",
    items: [
      { name: "Tobikko (500g/pkt)", unit: "PKT" },
      { name: "Boneless Chicken Leg (2kg/pkt)", unit: "KG" },
      { name: "Cotton Glove (12pc/pkt)", unit: "PKT" },
      { name: "Crushed Peanut (kg/pkt)", unit: "KG" },
      { name: "Jipaitan (kg/pkt)", unit: "PKT" },
      { name: "Diced Sliced Garlic (kg/pkt)", unit: "PKT" },
      { name: "Fried Minced Garlic (kg/pkt)", unit: "PKT" },
      { name: "Honey (kg/tub)", unit: "TUB" },
      { name: "Oyster Sauce Panda (2.27kg/tin)", unit: "TIN" },
      { name: "Parmesan Hard Cheese", unit: "KG" },
      { name: "Unsalted Butter", unit: "PCS" },
      { name: "Schweppes Soda (24can/ctn)", unit: "CTN" },
      { name: "Black Nitrile Glove (M)", unit: "BOX" },
      { name: "Black Nitrile Glove (L)", unit: "BOX" },
      { name: "Prawn", unit: "KG" },
      { name: "Black Fungus", unit: "KG" },
      { name: "Rice Cake", unit: "PKT" },
    ],
  },
  {
    supplier: "Toho",
    items: [
      { name: "Tobikko (500g/box)", unit: "BOX" },
      { name: "Tempura Bits (kg/pkt)", unit: "PKT" },
      { name: "Kikkoman", unit: "BTL" },
      { name: "Shoyu", unit: "BTL" },
      { name: "Jipaitan (kg/pkt)", unit: "PKT" },
      { name: "Tempura Paper", unit: "PKT" },
      { name: "Udon Noodle", unit: "PKT" },
      { name: "Hondashi", unit: "PKT" },
      { name: "Chicken Stock", unit: "BTL" },
      { name: "Sweet Sauce (Mirin)", unit: "TUB" },
      { name: "Miso", unit: "PKT" },
      { name: "Bonito Flakes", unit: "PKT" },
      { name: "Tongarashi (kg/pkt)", unit: "PKT" },
    ],
  },
  {
    supplier: "New Deli",
    items: [
      { name: "Kitchen Towel", unit: "PKT" },
      { name: "Thai Rice", unit: "PKT" },
      { name: "Good Morning Towel", unit: "PC" },
      { name: "Gas Casette", unit: "BTL" },
      { name: "Baking Paper", unit: "ROLL" },
      { name: "LKK Dark Soy Sauce", unit: "BTL" },
      { name: "Pineapple Sliced", unit: "TIN" },
      { name: "Mona Cooking Oil", unit: "TIN" },
      { name: "Black Garlic Flakes", unit: "KG" },
      { name: "Black Pepper Corn (kg/pkt)", unit: "KG" },
      { name: "Black Pepper Crushed (kg/pkt)", unit: "KG" },
      { name: "Cling Wrap 6x30cm", unit: "ROLL" },
      { name: "Cling Wrap 6x45cm", unit: "ROLL" },
      { name: "Dried Pine Nut", unit: "KG" },
      { name: "Dried Red Date", unit: "KG" },
      { name: "Masking Tape", unit: "ROLL" },
      { name: "Mozz Shredded", unit: "KG" },
      { name: "Ginseng Root (kg/pkt)", unit: "PKT" },
      { name: "Glutinous Rice Flour (600g/pkt)", unit: "PKT" },
    ],
  },
  {
    supplier: "Central Kitchen",
    items: [
      { name: "Bibim Noodle Sauce", unit: "KG" },
      { name: "Cabbage Pickle", unit: "KG" },
      { name: "Chicken Dipping Paste", unit: "KG" },
      { name: "Gizzard", unit: "KG" },
      { name: "Heart", unit: "KG" },
      { name: "Neck", unit: "KG" },
      { name: "Softbone", unit: "KG" },
      { name: "Tender", unit: "KG" },
      { name: "Thigh", unit: "KG" },
      { name: "Thigh Marinated Sauce", unit: "KG" },
      { name: "Garlic Sauce", unit: "KG" },
      { name: "Gizzard Popcorn", unit: "KG" },
      { name: "Hangover Soup Paste", unit: "KG" },
      { name: "Minari Sauce", unit: "KG" },
      { name: "Mushroom Paste", unit: "KG" },
      { name: "Radish Kimchi", unit: "KG" },
      { name: "Sliced Chilli Pickle", unit: "KG" },
      { name: "Sriracha Mayo", unit: "KG" },
      { name: "Yuzu Kosho", unit: "KG" },
    ],
  },
  {
    supplier: "Avo & Co",
    items: [
      { name: "Truffle Salsa Paste (960g)", unit: "BTL" },
      { name: "White Truffle Oil (1L)", unit: "BTL" },
      { name: "Truffle", unit: "KG" },
    ],
  },
  {
    supplier: "Creme Works",
    items: [
      { name: "Vegan Sundubu Gelato", unit: "TUB" },
    ],
  },
  {
    supplier: "HQ & Overflow (Korea Stock)",
    items: [
      { name: "Perilla Oil (1.8L)", unit: "BTL" },
      { name: "Perilla Seed (500g/pkt)", unit: "PKT" },
      { name: "Herb for Samgyetang", unit: "PKT" },
      { name: "Sancho Powder", unit: "PKT" },
      { name: "Watersnail (kg/pkt)", unit: "KG" },
      { name: "Ongshimi (800g/pkt)", unit: "PKT" },
      { name: "Anchovy Powder (kg/pkt)", unit: "PKT" },
      { name: "Minari (4kg/ctn)", unit: "CTN" },
      { name: "Mustard Pickle", unit: "KG" },
    ],
  },
  {
    supplier: "Toh Thye San",
    items: [
      { name: "Neck", unit: "KG" },
      { name: "Stuffed Chicken", unit: "KG" },
      { name: "Chicken Feet", unit: "KG" },
      { name: "Chicken Leg Boneless Mince", unit: "KG" },
      { name: "Chicken Skin", unit: "KG" },
      { name: "Boneless Chicken Feet", unit: "PKT" },
    ],
  },
  {
    supplier: "Culina",
    items: [
      { name: "Free Range Eggs", unit: "TRAY" },
    ],
  },
  {
    supplier: "Lim Joo Huat",
    items: [
      { name: "Bean Sprout", unit: "KG" },
      { name: "Carrot", unit: "KG" },
      { name: "Cherry Tomato", unit: "KG" },
      { name: "Chive (50g/pkt)", unit: "PKT" },
      { name: "Egg (30pc/tray)", unit: "TRAY" },
      { name: "Enoki (~135g/pkt)", unit: "PKT" },
      { name: "Garlic Peeled (500g/pkt)", unit: "PKT" },
      { name: "Gingko Nut", unit: "PKT" },
      { name: "Japanese Cucumber", unit: "KG" },
      { name: "King Oyster (200g/pkt)", unit: "PKT" },
      { name: "Leek (Japanese)", unit: "KG" },
      { name: "Lemon (200g)", unit: "PC" },
      { name: "Lettuce Red", unit: "KG" },
      { name: "Onion Peeled", unit: "KG" },
      { name: "Radish White", unit: "KG" },
      { name: "Red Onion Peeled", unit: "KG" },
      { name: "Shiitake", unit: "KG" },
      { name: "Shimeiji (150g/pkt)", unit: "PKT" },
      { name: "Shishito Chilli", unit: "KG" },
      { name: "Spring Onion", unit: "KG" },
      { name: "Tau Kwa (Unicard) (400g)", unit: "PC" },
      { name: "Tofu Red (Silken) (300g)", unit: "PKT" },
      { name: "Zucchini", unit: "KG" },
    ],
  },
  {
    supplier: "Sing Seng",
    items: [
      { name: "Soybean Sprout", unit: "KG" },
      { name: "Carrot", unit: "KG" },
      { name: "Cherry Tomato", unit: "KG" },
      { name: "Eggplant", unit: "PKT" },
      { name: "Egg (30pc/tray)", unit: "TRAY" },
      { name: "Enoki (~135g/pkt)", unit: "PKT" },
      { name: "Garlic Peeled (kg/pkt)", unit: "PKT" },
      { name: "Japanese Cucumber", unit: "KG" },
      { name: "King Oyster (200g/pkt)", unit: "PKT" },
      { name: "Leek", unit: "CTN" },
      { name: "Lemon (200g)", unit: "PC" },
      { name: "Lettuce Red", unit: "KG" },
      { name: "Onion Peeled", unit: "PKT" },
      { name: "Radish White", unit: "KG" },
      { name: "Red Onion Peeled", unit: "PKT" },
      { name: "Shiitake", unit: "PKT" },
      { name: "Shimeiji (150g/pkt)", unit: "PKT" },
      { name: "Spring Onion", unit: "KG" },
      { name: "Tau Kwa (Fortune) (400g)", unit: "PKT" },
      { name: "Silken Tofu (Fortune)", unit: "PKT" },
      { name: "Zucchini", unit: "KG" },
    ],
  },
  {
    supplier: "Koryo",
    items: [
      { name: "Frying Powder (kg/pkt)", unit: "PKT" },
      { name: "Hot Bean Paste", unit: "TUB" },
      { name: "Soybean Paste", unit: "TUB" },
      { name: "White Sugar (kg/pkt)", unit: "PKT" },
      { name: "Miwon (kg/pkt)", unit: "PKT" },
      { name: "Dried Laver Roasted Kimbab (20g/pkt)", unit: "PKT" },
      { name: "Dry Dashima (Kelp) (150g/pkt)", unit: "PKT" },
      { name: "Mul Yet (5kg)", unit: "EA" },
      { name: "Chilli Powder Coarse (kg/pkt)", unit: "PKT" },
      { name: "Chilli Powder Fine (kg/pkt)", unit: "PKT" },
      { name: "Glutinous Rice", unit: "PKT" },
      { name: "Black Pepper Powder", unit: "PKT" },
      { name: "Fried Bean Powder", unit: "PKT" },
      { name: "Fried Sesame Black", unit: "PKT" },
      { name: "Fried Sesame White", unit: "PKT" },
      { name: "Perilla Powder White", unit: "KG" },
      { name: "Potato Starch", unit: "PKT" },
      { name: "Pickled Radish", unit: "PKT" },
      { name: "Chung Kuk Jang", unit: "PKT" },
      { name: "Sesame Oil", unit: "BTL" },
      { name: "Green Plum Extract", unit: "BTL" },
      { name: "Sliced Seasoned Laver", unit: "PKT" },
      { name: "Kalguksu (kg/pkt)", unit: "PKT" },
      { name: "Chilli Oil", unit: "BTL" },
      { name: "Wheat Noodle Regular", unit: "PKT" },
      { name: "Flower Salt", unit: "PKT" },
      { name: "Soy Sauce Jin (15L)", unit: "DRUM" },
    ],
  },
  {
    supplier: "Allied Food",
    items: [
      { name: "Hetban Cooked Rice", unit: "PKT" },
      { name: "Vinegar (15L)", unit: "BTL" },
      { name: "Sesame Oil", unit: "BTL" },
      { name: "Seasoned Salt", unit: "PKT" },
      { name: "Shokaku Premium Rice", unit: "PKT" },
    ],
  },
  {
    supplier: "Hansing Food",
    items: [
      { name: "Glutinous Rice Powder (kg/pkt)", unit: "PKT" },
      { name: "Spicy Chilli Powder (2.5kg/pkt)", unit: "PKT" },
    ],
  },
];

export default monthlyStock;
