const products = [
  { name: "Anchovy Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Awase Miso", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Baked Chicken Bone and Feet", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Beef Dasida", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Black Pepper Corn", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Black Pepper Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Black Sesame Seed", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Blended Mushroom", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Boneless Chicken Feet", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Brown Pear", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Charcoal Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Charcoal Powder Mix", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Cheonggukjang", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Chicken", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Chicken Broth", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Chicken Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Chicken Thigh", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Chili Oil", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Chili Powder Coarse", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Chili Powder Fine", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Chye Sim", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Coarse Chili Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Coarse Sea Salt", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Collegen Paitan", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Cooked Rice", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Cooking Oil", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Corn Oil", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Corn Syrup", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Crushed Peanuts", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Dark Soy Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Dried Chili", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Egg", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Eggplant", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Eggplant Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Enoki", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Fine Chili Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Fish Roe", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Fish Roe Mix", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Fish Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Flower Salt", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Fried Gizzard", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Fried Mushrooms", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Frying Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Frying Powder Mix", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Garlic", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Ginseng", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Gizzard (Cut)", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Glutinous Rice Flour", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Gochujan", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Green Chili", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Green Chili Padi", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Green Chili Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Hangover Paste", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Hihashimaru Shoyu", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Hondashi", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Honey", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Honey Ginger Cheong", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Hwanman Vinegar", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Jin Soy Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Kanari Fish Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Katsuobushi", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Kelp", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Kikkoman Soy Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Kimchi Paste", price: 0, weight: { value: 0, unit: "g" } },
  { name: "King Oyster Mushroom", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Korean Chili Paste", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Korean Spicy Chilli Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Leek", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Liquid Chicken MSG", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Marinated Boneless Chicken Feet", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Marinated Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Mayonnaise", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Minced Chicken", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Minced Garlic", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Miso Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Miwon", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Napa Cabbage", price: 0, weight: { value: 0, unit: "g" } },
  { name: "New sugar", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Non Alcohol Mirin", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Oyster Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Perilla Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Perilla Powder Mix", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Plum Extract", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Potato Starch", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Radish", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Red Cheongyang Chilli Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Red Chili", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Red Chili Padi", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Red Date", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Rice", price: 47.50, weight: { value: 5000, unit: "g" } },
  { name: "Rice Ball", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Rice Wine", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Salted Prawn", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Samgyetang Herbal", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Sancho Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Sancho Soy Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Seasoned Salt", price: 5, weight: { value: 1000, unit: "g" } },
  { name: "Seaweed Flake", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Sesame B/W", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Sesame Oil", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Sesame Seeds", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Shimeji", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Shitake", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Sichimi", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Soaked Kelp", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Soda", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Soy Bean Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Soy Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Soybean Paste", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Spring Onion", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Spring Onion (White Part)", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Spring Onions (Sliced)", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Sprite", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Sriracha Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Tempura Dipping Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Tenkasu", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Thai Fish Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Thai Holy Basil", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Truffle Paste", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Truffle Powder Mix", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Udon Broth", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Udon Noodle", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Udon Seasonings", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Unsalted Butter", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Vietnamese Dried Chili", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Vinegar", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Water", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Water for Potato Starch", price: 0, weight: { value: 0, unit: "g" } },
  { name: "White Onion", price: 0, weight: { value: 0, unit: "g" } },
  { name: "White Radish", price: 0, weight: { value: 0, unit: "g" } },
  { name: "White Sesame Seed", price: 0, weight: { value: 0, unit: "g" } },
  { name: "White Sugar", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Yellow Radish", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Yuju Cheong", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Zucchini", price: 0, weight: { value: 0, unit: "g" } }
];

export default products;
