const products = [
  { name: "Anchovy Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Awase Miso", price: 3.5, weight: { value: 650, unit: "g" } },
  { name: "Baked Chicken Bone and Feet", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Beef Dasida", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Black Pepper Corn", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Black Pepper Powder", price: 32, weight: { value: 1000, unit: "g" } },
  { name: "Black Sesame Seed", price: 5.5, weight: { value: 1000, unit: "g" } },
  { name: "Blended Mushroom", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Boneless Chicken Feet", price: 2.8, weight: { value: 1000, unit: "g" } },
  { name: "Brown Pear", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Charcoal Powder", price: 1.65, weight: { value: 100, unit: "g" } },
  { name: "Charcoal Powder Mix", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Cheonggukjang", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Chicken", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Chicken Broth", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Chicken Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Chicken Thigh", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Chili Oil", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Chili Powder Coarse", price: 10.6, weight: { value: 1000, unit: "g" } },
  { name: "Chili Powder Fine", price: 11.8, weight: { value: 1000, unit: "g" } },
  { name: "Chye Sim", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Coarse Chili Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Coarse Sea Salt", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Collegen Paitan", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Cooked Rice", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Cooking Oil", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Corn Oil", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Corn Syrup", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Crushed Peanuts", price: 6.8, weight: { value: 1000, unit: "g" } },
  { name: "Dark Soy Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Dried Chili", price: 8.8, weight: { value: 1000, unit: "g" } },
  { name: "Egg", price: 9, weight: { value: 1800, unit: "g" } },
  { name: "Eggplant", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Eggplant Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Enoki", price: 0.7, weight: { value: 150, unit: "g" } },
  { name: "Fine Chili Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Fish Roe", price: 31, weight: { value: 500, unit: "g" } },
  { name: "Fish Roe Mix", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Fish Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Flower Salt", price: 2.7, weight: { value: 1000, unit: "g" } },
  { name: "Fried Gizzard", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Fried Mushrooms", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Frying Powder", price: 3, weight: { value: 1000, unit: "g" } },
  { name: "Frying Powder Mix", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Garlic", price: 1.75, weight: { value: 500, unit: "g" } },
  { name: "Ginseng", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Gizzard (Cut)", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Glutinous Rice Flour", price: 1.6, weight: { value: 600, unit: "g" } },
  { name: "Gochujan", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Green Chili", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Green Chili Padi", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Green Chili Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Hangover Paste", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Hihashimaru Shoyu", price: 8.5, weight: { value: 1800, unit: "g" } },
  { name: "Hondashi", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Honey", price: 5.5, weight: { value: 1000, unit: "g" } },
  { name: "Honey Ginger Cheong", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Hwanman Vinegar", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Jin Soy Sauce", price:28.5, weight: { value: 1500, unit: "g" } },
  { name: "Kanari Fish Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Katsuobushi", price: 14.5, weight: { value: 500, unit: "g" } },
  { name: "Kelp", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Kikkoman Soy Sauce", price: 10.5, weight: { value: 1600, unit: "g" } },
  { name: "Kimchi Paste", price: 0, weight: { value: 0, unit: "g" } },
  { name: "King Oyster Mushroom", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Korean Chili Paste", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Korean Spicy Chilli Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Leek", price: 4.5, weight: { value: 1000, unit: "g" } },
  { name: "Liquid Chicken MSG", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Marinated Boneless Chicken Feet", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Marinated Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Mayonnaise", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Minced Chicken", price: 5.5, weight: { value: 500, unit: "g" } },
  { name: "Minced Garlic", price: 1.75, weight: { value: 1000, unit: "g" } },
  { name: "Miso Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Miwon", price: 25.6, weight: { value: 1000, unit: "g" } },
  { name: "Napa Cabbage", price: 0, weight: { value: 0, unit: "g" } },
  { name: "New sugar", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Non Alcohol Mirin", price: 50, weight: { value: 18000, unit: "g" } },
  { name: "Oyster Sauce", price: 10, weight: { value: 2270, unit: "g" } },
  { name: "Perilla Powder", price: 31.8, weight: { value: 1000, unit: "g" } },
  { name: "Perilla Powder Mix", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Plum Extract", price: 11.7, weight: { value: 1500, unit: "g" } },
  { name: "Potato Starch", price: 2.8, weight: { value: 500, unit: "g" } },
  { name: "Radish", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Red Cheongyang Chilli Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Red Chili", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Red Chili Padi", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Red Date", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Rice", price: 47.50, weight: { value: 2500, unit: "g" } },
  { name: "Rice Ball", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Rice Wine", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Salted Prawn", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Samgyetang Herbal", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Sancho Powder", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Sancho Soy Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Seasoned Salt", price: 3.5, weight: { value: 1000, unit: "g" } },
  { name: "Seaweed Flake", price: 33.6, weight: { value: 1000, unit: "g" } },
  { name: "Sesame B/W", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Sesame Oil", price: 32, weight: { value: 1800, unit: "g" } },
  { name: "Sesame Seeds", price: 11, weight: { value: 1000, unit: "g" } },
  { name: "Shimeji", price: 0.9, weight: { value: 200, unit: "g" } },
  { name: "Shitake", price: 6.8, weight: { value: 1000, unit: "g" } },
  { name: "Sichimi", price: 15, weight: { value: 1000, unit: "g" } },
  { name: "Soaked Kelp", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Soda", price: 0.75, weight: { value: 330, unit: "g" } },
  { name: "Soy Bean Powder", price: 4, weight: { value: 400, unit: "g" } },
  { name: "Soy Sauce", price: 28.5, weight: { value: 1500, unit: "g" } },
  { name: "Soybean Paste", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Spring Onion", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Spring Onion (White Part)", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Spring Onions (Sliced)", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Sprite", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Sriracha Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Tempura Dipping Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Tenkasu", price: 8.5, weight: { value: 1000, unit: "g" } },
  { name: "Thai Fish Sauce", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Thai Holy Basil", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Truffle Paste", price: 36, weight: { value: 960, unit: "g" } },
  { name: "Truffle Powder Mix", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Udon Broth", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Udon Noodle", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Udon Seasonings", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Unsalted Butter", price: 4.02, weight: { value: 250, unit: "g" } },
  { name: "Vietnamese Dried Chili", price: 8.8, weight: { value: 1000, unit: "g" } },
  { name: "Vinegar", price: 25.5, weight: { value: 1500, unit: "g" } },
  { name: "Water", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Water for Potato Starch", price: 0, weight: { value: 0, unit: "g" } },
  { name: "White Onion", price: 1.9, weight: { value: 1000, unit: "g" } },
  { name: "White Radish", price: 0, weight: { value: 0, unit: "g" } },
  { name: "White Sesame Seed", price: 17.8, weight: { value: 1000, unit: "g" } },
  { name: "White Sugar", price: 2.1, weight: { value: 1000, unit: "g" } },
  { name: "Yellow Radish", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Yuju Cheong", price: 0, weight: { value: 0, unit: "g" } },
  { name: "Zucchini", price: 0, weight: { value: 0, unit: "g" } }
];

export default products;
